### PR TITLE
Passing the hostname explicitly

### PR DESCRIPTION
**Pull request by Fokko**
Hi,

I had some troubles setting up the environment using the docker-compose image. Found out that Spark listens on the IP of the container, instead of the hostname. This prohibits the client to register at the master. Passing the hostname explicitly fixes this.

``` python
master_1 | Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
master_1 | 15/07/01 11:26:33 INFO Master: Registered signal handlers for [TERM, HUP, INT]
master_1 | 15/07/01 11:26:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
master_1 | 15/07/01 11:26:34 INFO SecurityManager: Changing view acls to: root
master_1 | 15/07/01 11:26:34 INFO SecurityManager: Changing modify acls to: root
master_1 | 15/07/01 11:26:34 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
worker_1 | Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
worker_1 | 15/07/01 11:26:35 INFO Worker: Registered signal handlers for [TERM, HUP, INT]
master_1 | 15/07/01 11:26:35 INFO Slf4jLogger: Slf4jLogger started
master_1 | 15/07/01 11:26:35 INFO Remoting: Starting remoting
master_1 | 15/07/01 11:26:35 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkMaster@172.17.0.160:7077]
master_1 | 15/07/01 11:26:35 INFO Utils: Successfully started service 'sparkMaster' on port 7077.
worker_1 | 15/07/01 11:26:35 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
worker_1 | 15/07/01 11:26:36 INFO SecurityManager: Changing view acls to: root
worker_1 | 15/07/01 11:26:36 INFO SecurityManager: Changing modify acls to: root
worker_1 | 15/07/01 11:26:36 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
master_1 | 15/07/01 11:26:36 INFO Utils: Successfully started service on port 6066.
master_1 | 15/07/01 11:26:36 INFO StandaloneRestServer: Started REST server for submitting applications on port 6066
master_1 | 15/07/01 11:26:36 INFO Master: Starting Spark master at spark://172.17.0.160:7077
master_1 | 15/07/01 11:26:36 INFO Master: Running Spark version 1.4.0
master_1 | 15/07/01 11:26:36 INFO Utils: Successfully started service 'MasterUI' on port 8080.
master_1 | 15/07/01 11:26:36 INFO MasterWebUI: Started MasterWebUI at http://172.17.0.160:8080
master_1 | 15/07/01 11:26:36 INFO Master: I have been elected leader! New state: ALIVE
worker_1 | 15/07/01 11:26:36 INFO Slf4jLogger: Slf4jLogger started
worker_1 | 15/07/01 11:26:36 INFO Remoting: Starting remoting
worker_1 | 15/07/01 11:26:37 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkWorker@172.17.0.162:8881]
worker_1 | 15/07/01 11:26:37 INFO Utils: Successfully started service 'sparkWorker' on port 8881.
worker_1 | 15/07/01 11:26:37 INFO Worker: Starting Spark worker 172.17.0.162:8881 with 2 cores, 1024.0 MB RAM
worker_1 | 15/07/01 11:26:37 INFO Worker: Running Spark version 1.4.0
worker_1 | 15/07/01 11:26:37 INFO Worker: Spark home: /usr/spark
worker_1 | 15/07/01 11:26:37 INFO Utils: Successfully started service 'WorkerUI' on port 8081.
worker_1 | 15/07/01 11:26:37 INFO WorkerWebUI: Started WorkerWebUI at http://172.17.0.162:8081
worker_1 | 15/07/01 11:26:37 INFO Worker: Connecting to master akka.tcp://sparkMaster@master:7077/user/Master...
worker_1 | 15/07/01 11:26:49 INFO Worker: Retrying connection to master (attempt # 1)
worker_1 | 15/07/01 11:26:49 INFO Worker: Connecting to master akka.tcp://sparkMaster@master:7077/user/Master...
worker_1 | 15/07/01 11:27:01 INFO Worker: Retrying connection to master (attempt # 2)
worker_1 | 15/07/01 11:27:01 INFO Worker: Connecting to master akka.tcp://sparkMaster@master:7077/user/Master...
worker_1 | 15/07/01 11:27:13 INFO Worker: Retrying connection to master (attempt # 3)
worker_1 | 15/07/01 11:27:13 INFO Worker: Connecting to master akka.tcp://sparkMaster@master:7077/user/Master...
worker_1 | 15/07/01 11:27:25 INFO Worker: Retrying connection to master (attempt # 4)
worker_1 | 15/07/01 11:27:25 INFO Worker: Connecting to master akka.tcp://sparkMaster@master:7077/user/Master...
worker_1 | 15/07/01 11:27:37 INFO Worker: Retrying connection to master (attempt # 5)
worker_1 | 15/07/01 11:27:37 INFO Worker: Connecting to master akka.tcp://sparkMaster@master:7077/user/Master...
worker_1 | 15/07/01 11:27:49 INFO Worker: Retrying connection to master (attempt # 6)
worker_1 | 15/07/01 11:27:49 INFO Worker: Connecting to master akka.tcp://sparkMaster@master:7077/user/Master...
worker_1 | 15/07/01 11:29:03 INFO Worker: Retrying connection to master (attempt # 7)
worker_1 | 15/07/01 11:29:03 INFO Worker: Connecting to master akka.tcp://sparkMaster@master:7077/user/Master...
```

After the fix the worker directly connects to the master:

``` python
master_1 | Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
master_1 | 15/07/01 11:31:46 INFO Master: Registered signal handlers for [TERM, HUP, INT]
master_1 | 15/07/01 11:31:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
master_1 | 15/07/01 11:31:47 INFO SecurityManager: Changing view acls to: root
master_1 | 15/07/01 11:31:47 INFO SecurityManager: Changing modify acls to: root
master_1 | 15/07/01 11:31:47 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
worker_1 | Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
worker_1 | 15/07/01 11:31:48 INFO Worker: Registered signal handlers for [TERM, HUP, INT]
master_1 | 15/07/01 11:31:48 INFO Slf4jLogger: Slf4jLogger started
master_1 | 15/07/01 11:31:48 INFO Remoting: Starting remoting
master_1 | 15/07/01 11:31:48 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkMaster@master:7077]
master_1 | 15/07/01 11:31:48 INFO Utils: Successfully started service 'sparkMaster' on port 7077.
worker_1 | 15/07/01 11:31:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
worker_1 | 15/07/01 11:31:49 INFO SecurityManager: Changing view acls to: root
worker_1 | 15/07/01 11:31:49 INFO SecurityManager: Changing modify acls to: root
worker_1 | 15/07/01 11:31:49 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
master_1 | 15/07/01 11:31:49 INFO Utils: Successfully started service on port 6066.
master_1 | 15/07/01 11:31:49 INFO StandaloneRestServer: Started REST server for submitting applications on port 6066
master_1 | 15/07/01 11:31:49 INFO Master: Starting Spark master at spark://master:7077
master_1 | 15/07/01 11:31:49 INFO Master: Running Spark version 1.4.0
master_1 | 15/07/01 11:31:49 INFO Utils: Successfully started service 'MasterUI' on port 8080.
master_1 | 15/07/01 11:31:49 INFO MasterWebUI: Started MasterWebUI at http://172.17.0.164:8080
master_1 | 15/07/01 11:31:49 INFO Master: I have been elected leader! New state: ALIVE
worker_1 | 15/07/01 11:31:49 INFO Slf4jLogger: Slf4jLogger started
worker_1 | 15/07/01 11:31:49 INFO Remoting: Starting remoting
worker_1 | 15/07/01 11:31:50 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkWorker@172.17.0.166:8881]
worker_1 | 15/07/01 11:31:50 INFO Utils: Successfully started service 'sparkWorker' on port 8881.
worker_1 | 15/07/01 11:31:50 INFO Worker: Starting Spark worker 172.17.0.166:8881 with 2 cores, 1024.0 MB RAM
worker_1 | 15/07/01 11:31:50 INFO Worker: Running Spark version 1.4.0
worker_1 | 15/07/01 11:31:50 INFO Worker: Spark home: /usr/spark
worker_1 | 15/07/01 11:31:50 INFO Utils: Successfully started service 'WorkerUI' on port 8081.
worker_1 | 15/07/01 11:31:50 INFO WorkerWebUI: Started WorkerWebUI at http://172.17.0.166:8081
worker_1 | 15/07/01 11:31:50 INFO Worker: Connecting to master akka.tcp://sparkMaster@master:7077/user/Master...
master_1 | 15/07/01 11:31:51 INFO Master: Registering worker 172.17.0.166:8881 with 2 cores, 1024.0 MB RAM
worker_1 | 15/07/01 11:31:51 INFO Worker: Successfully registered with master spark://master:7077
```

### CODE REVIEW

**Comment by EncodePanda** [comment]
Awesome man! This should be merged to master ASAP ! Thanks @Fokko :)

**Comment by dylanmei** [comment]
@Fokko I appreciate the PR, but there's opinionated bits here that are to do with more than the hostname fix.

Would you consider submitting the docker-compose "task" container as a separate pull request? There should be no need to include a jar in the PR, as Spark comes with a  `$SPARK_HOME/lib/spark-examples...jar` for running the SparkPi example.

**Comment by EncodePanda** [comment]
Current solution is not working. There must be at least added  " -h master" to the master->command in docker-compose.yml

**Comment by dylanmei** [comment]
The `-h hostname` fix was applied in b557c8490fc01943c131fd9534d1b25ca6e61fbc. A SparkPi example has been added via 0d12171dd3e25781970f8d1f04a06fabc252ad69.

Closing this, thanks

**Pull request closed without merging**
