### PR TITLE
Bump to Spark 2.1.0

### PR DESCRIPTION
**Pull request by transistorize**
Everything else was left the same.

### CODE REVIEW

**Comment by transistorize** [comment]
@dylanmei I don't seem to have merge abilities. I'm sorry to bother you, but perhaps you can merge and build the new image?

**Comment by dylanmei** [comment]
@transistorize I am no longer a part of the org! @daplho @justinclayton can help.

**Comment by mikeklein13** [comment]
👍

**Comment by daplho** [comment]
merged

**Pull request merged**
