### PR TITLE
Bump to Spark 2.0.1

### PR DESCRIPTION
**Pull request by transistorize**

### CODE REVIEW

**Comment by dylanmei** [comment]
Great, thanks! I'll post here when the Docker hub build is complete.

**Comment by dylanmei** [comment]
Done. :tada:

**Comment by transistorize** [comment]
Thanks @dylanmei! The Java version could use a bump too, not sure if you wanted that as a separate update.

**Comment by dylanmei** [comment]
A separate update would be welcome.

**Pull request merged**
