### PR TITLE
Bump to Spark 2.2.1

### PR DESCRIPTION
**Pull request by krystiannowak**

### CODE REVIEW

**Comment by krystiannowak** [comment]
@dylanmei - not sure why we can't just download Spark binary (the one without Hadoop) directly from http://archive.apache.org/dist/spark/spark-2.2.1/ the same way as the Hadoop distribution is downloaded - do you have any hint? In terms of geo-distribution [the dynamic Lua closer script](https://svn.apache.org/repos/asf/infrastructure/site/trunk/content/dyn/closer.lua) be used as in this PR.

**Comment by aigor** [comment]
Wote for this pull request!

**Comment by dylanmei** [comment]
@krystiannowak before 2.2.1 the CF url was both reliable and fast. Seems like the archives aren't being placed here anymore. cc @bryceageno

**Comment by bryceageno** [comment]
@krystiannowak sorry for being a little late.

**Comment by krystiannowak** [comment]
@bryceageno No worries! Best is it finally appeared on https://hub.docker.com/r/gettyimages/spark/tags/ :)

**Pull request merged**
